
airbnb:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: UFCPBJF-EV19764
      user: dbt
      role: TRANSFORM
      private_key_path: "/workspaces/dbt-student-repo/airbnb/rsa_key.p8"
      database: AIRBNB
      schema: DEV
      threads: 1
      warehouse: COMPUTE_WH

